# Generated by Django 3.2.6 on 2021-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='book',
        ),
        migrations.AddField(
            model_name='tag',
            name='book',
            field=models.ManyToManyField(to='book.Book'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
