# Generated by Django 3.2.6 on 2021-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210812_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='book.Tag'),
        ),
    ]
