# Generated by Django 3.2.6 on 2021-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210812_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(to='book.Writer'),
        ),
    ]
